# Map size parameters
BOARD_SIZE = 20
CELL_SIZE = 25
WIDTH = 800
HEIGHT = BOARD_SIZE * CELL_SIZE

# Sidebar parameters
SIDEBAR_WIDTH = 150
SIDEBAR_X_START = WIDTH - SIDEBAR_WIDTH
CELL_CATALOGUE_SIZE = 50
CELL_CATALOGUE_PADDING_X = 25
CELL_CATALOGUE_PADDING_Y = 50
CELL_CATALOGUE_INTERLINE_PADDING = 10
CATALOGUE_X_START = SIDEBAR_X_START + CELL_CATALOGUE_PADDING_X
CATALOGUE_X_END = CATALOGUE_X_START + CELL_CATALOGUE_SIZE